[build]
  publish = "."
  functions = "netlify/functions"

# SPA fallback (si usás navegación interna / rutas)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
